CREATE DATABASE IF NOT EXISTS vagasparadevs;

CREATE TABLE IF NOT EXISTS vaga(
	id BIGINT AUTO_INCREMENT NOT NULL,
    nome VARCHAR(50) NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	data DATE NOT NULL,
	salario DECIMAL(10,2) NOT NULL,
    PRIMARY KEY(id)    
)ENGINE=InnoDB DEFAULT CHARSET=utf8;