CREATE TABLE IF NOT EXISTS candidato(
	id BIGINT AUTO_INCREMENT NOT NULL,
    nome_candidato VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;